<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_People</name>
   <tag></tag>
   <elementGuidId>e3334899-d831-4d9c-9b29-21b0cbbe3d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='modalDescription']/div[2]/div/div/button[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a52602b-9e7f-4edb-9048-4058205f7e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      People
      </value>
      <webElementGuid>a1763cb3-b804-482a-8cb8-9cf22bc2816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDescription&quot;)/div[2]/div[@class=&quot;tabbed-unit&quot;]/div[@class=&quot;tabbed-unit__tabs&quot;]/button[4]</value>
      <webElementGuid>186984b1-0fde-48cb-ab69-f431478f2ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='modalDescription']/div[2]/div/div/button[4]</value>
      <webElementGuid>d8bfc9ab-bdfd-4a09-9246-a49819174628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment &amp; Exposure Risks'])[1]/following::button[1]</value>
      <webElementGuid>98a67b84-2128-4344-bed8-be1d4b5a53e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Throughput'])[2]/following::button[2]</value>
      <webElementGuid>5dc954fd-74eb-4430-aae3-c2a3c15445bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Recovery'])[1]/preceding::button[1]</value>
      <webElementGuid>eb9cf03a-c13e-4620-9dc8-8130650bfe4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Issue(s)'])[1]/preceding::button[2]</value>
      <webElementGuid>019e8e73-22c9-478c-8172-57c966507144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='People']/parent::*</value>
      <webElementGuid>ce29a9d3-9b15-4824-9f78-b3767bbb50fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>97b1385c-9d2c-45e9-816c-03b776196551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
      People
      ' or . = '
      People
      ')]</value>
      <webElementGuid>0f86afdb-2455-447c-bb86-ebabcac1e2e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
