<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_S</name>
   <tag></tag>
   <elementGuidId>343349ed-8320-4a72-8af6-ac1db5871c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='safetyhuddle']/section[2]/div/div[5]/div/div[2]/section/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d84e0c43-c54f-4844-9aab-47fb4d5a23c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-letter</value>
      <webElementGuid>f09b17eb-4de6-431b-8518-f446fd7e3132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            S
          </value>
      <webElementGuid>d9e32860-4c52-4e46-9304-74583f5ee76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;safetyhuddle&quot;)/section[@class=&quot;list&quot;]/div[@class=&quot;department-list&quot;]/div[@class=&quot;department-card&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;header-right&quot;]/section[@class=&quot;alerts&quot;]/span[@class=&quot;yellow&quot;]/span[@class=&quot;alert-letter&quot;]</value>
      <webElementGuid>eb560450-2d7e-4c21-a608-32ad9f141e1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safetyhuddle']/section[2]/div/div[5]/div/div[2]/section/span/span</value>
      <webElementGuid>42acd740-841a-4719-bbae-aa7ea7de78fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[8]/following::span[5]</value>
      <webElementGuid>1045c56d-89ac-4f53-b23f-a523d299d3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[4]/following::span[7]</value>
      <webElementGuid>8139a55c-78b0-42fa-ba1d-7d014ddf8b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[5]/preceding::span[1]</value>
      <webElementGuid>a547891f-e2c4-4a1b-b603-8c7b68fbb31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[5]/preceding::span[3]</value>
      <webElementGuid>8e212337-b84c-421e-9919-8c73ea5f5302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/section/span/span</value>
      <webElementGuid>82756de0-36cf-4cb8-9c72-ded59ddc4541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            S
          ' or . = '
            S
          ')]</value>
      <webElementGuid>f3592510-d79c-422e-a6eb-02db3f6ab6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
